apiVersion: v1
entries:
  blob-csi-driver:
  - apiVersion: v1
    appVersion: 1.25.0
    created: "2025-01-20T08:06:19.047777081Z"
    description: Azure Blob Storage CSI driver
    digest: de80f1865c1d95134dfc35faaa2c143c09957e3de6e07196aac5a54529fde9a6
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.25.0/blob-csi-driver-1.25.0.tgz
    version: 1.25.0
  - apiVersion: v1
    appVersion: v1.24.5
    created: "2025-01-20T08:06:19.047108961Z"
    description: Azure Blob Storage CSI driver
    digest: d8271336dabc6957f287488f97bc7189f1134d94f8a720359762c1adb24bb8cf
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.24.5/blob-csi-driver-v1.24.5.tgz
    version: v1.24.5
  - apiVersion: v1
    appVersion: v1.24.3
    created: "2025-01-20T08:06:19.046475715Z"
    description: Azure Blob Storage CSI driver
    digest: d8fac26124eaa218c4e3aeb187b8204c5266b4e4a3fca0df39e76376e846c8d8
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.24.3/blob-csi-driver-v1.24.3.tgz
    version: v1.24.3
  - apiVersion: v1
    appVersion: v1.24.2
    created: "2025-01-20T08:06:19.04581607Z"
    description: Azure Blob Storage CSI driver
    digest: 36567735f655d0c11a2b0247421a85577e5badd0a9413785075b29b58e2b049a
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.24.2/blob-csi-driver-v1.24.2.tgz
    version: v1.24.2
  - apiVersion: v1
    appVersion: v1.24.1
    created: "2025-01-20T08:06:19.045160033Z"
    description: Azure Blob Storage CSI driver
    digest: d4d98037428523005015a3f62441a7665b8a4126d39f7f0d563c474387edef0b
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.24.1/blob-csi-driver-v1.24.1.tgz
    version: v1.24.1
  - apiVersion: v1
    appVersion: v1.24.0
    created: "2025-01-20T08:06:19.044438607Z"
    description: Azure Blob Storage CSI driver
    digest: 183f724b7d67bf336de373b0e5ac22a50af63e42ff0e26ad73a7c11fd0ec6bfc
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.24.0/blob-csi-driver-v1.24.0.tgz
    version: v1.24.0
  - apiVersion: v1
    appVersion: v1.23.9
    created: "2025-01-20T08:06:19.043790924Z"
    description: Azure Blob Storage CSI driver
    digest: cb3b402c2ea03f71a7d57ae8f2d92181664489d4dd8f6130314f6dbd791871ab
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.23.9/blob-csi-driver-v1.23.9.tgz
    version: v1.23.9
  - apiVersion: v1
    appVersion: v1.23.7
    created: "2025-01-20T08:06:19.04303569Z"
    description: Azure Blob Storage CSI driver
    digest: 95f9e01cec77cda71ba7f556cf00ba377270df264aa11caf3d99062d959c8e66
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.23.7/blob-csi-driver-v1.23.7.tgz
    version: v1.23.7
  - apiVersion: v1
    appVersion: v1.23.4
    created: "2025-01-20T08:06:19.041409957Z"
    description: Azure Blob Storage CSI driver
    digest: 3ce2ee0c9255ebbd004fcdb9f3e5eb702b2203182eb7046754c9b2244c417b02
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.23.4/blob-csi-driver-v1.23.4.tgz
    version: v1.23.4
  - apiVersion: v1
    appVersion: v1.23.3
    created: "2025-01-20T08:06:19.040762117Z"
    description: Azure Blob Storage CSI driver
    digest: 55b2f47774558d16dec5c93655e5625634e35424466c10244fabd471c9b2a5c6
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.23.3/blob-csi-driver-v1.23.3.tgz
    version: v1.23.3
  - apiVersion: v1
    appVersion: v1.23.2
    created: "2025-01-20T08:06:19.040139059Z"
    description: Azure Blob Storage CSI driver
    digest: d85ba0c55d74c22b2b4cb964d70d8e38ede06f521cc5ca5502f57ed4b52d49f4
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.23.2/blob-csi-driver-v1.23.2.tgz
    version: v1.23.2
  - apiVersion: v1
    appVersion: v1.23.1
    created: "2025-01-20T08:06:19.039511303Z"
    description: Azure Blob Storage CSI driver
    digest: 66215f12a4e3acdcf09416d817b737e14546058b081a2cfd8bf9ef507229ca07
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.23.1/blob-csi-driver-v1.23.1.tgz
    version: v1.23.1
  - apiVersion: v1
    appVersion: v1.23.0
    created: "2025-01-20T08:06:19.038842929Z"
    description: Azure Blob Storage CSI driver
    digest: 57151e21e33660522f25694bd8ae985e5e17c7ffe09904ad2af4025e8bf1da72
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.23.0/blob-csi-driver-v1.23.0.tgz
    version: v1.23.0
  - apiVersion: v1
    appVersion: v1.22.9
    created: "2025-01-20T08:06:19.037913615Z"
    description: Azure Blob Storage CSI driver
    digest: 2ba7025c4c9917e5550b702c205ffd329ccec0a85b6a4fb74a4dc7206fa9ca64
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.22.9/blob-csi-driver-v1.22.9.tgz
    version: v1.22.9
  - apiVersion: v1
    appVersion: v1.22.8
    created: "2025-01-20T08:06:19.037261153Z"
    description: Azure Blob Storage CSI driver
    digest: a2ab602708e9c3b08d01baa66ffc7937b67119c060b4b90a41bedf15b709313c
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.22.8/blob-csi-driver-v1.22.8.tgz
    version: v1.22.8
  - apiVersion: v1
    appVersion: v1.22.6
    created: "2025-01-20T08:06:19.036589894Z"
    description: Azure Blob Storage CSI driver
    digest: ef7b5c287fca46351903cb819b3ccc8b8b2021addda87c59bea94d9ed61015a0
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.22.6/blob-csi-driver-v1.22.6.tgz
    version: v1.22.6
  - apiVersion: v1
    appVersion: v1.22.5
    created: "2025-01-20T08:06:19.03583252Z"
    description: Azure Blob Storage CSI driver
    digest: ff3c2c2e05dd048dd0af3e5c7d002eae2928a5d17fb269a1e4d5cadd30e8ab51
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.22.5/blob-csi-driver-v1.22.5.tgz
    version: v1.22.5
  - apiVersion: v1
    appVersion: v1.22.4
    created: "2025-01-20T08:06:19.034987865Z"
    description: Azure Blob Storage CSI driver
    digest: 6c38e79d2f50616daac0658cfa5b1a569e6ff8ce8f24ed40f563e87fb1d1340a
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.22.4/blob-csi-driver-v1.22.4.tgz
    version: v1.22.4
  - apiVersion: v1
    appVersion: v1.22.3
    created: "2025-01-20T08:06:19.033939045Z"
    description: Azure Blob Storage CSI driver
    digest: 6cdee296d22ecd330f477f2ca6da51b07320c546c04ae46c23eef48146b772c1
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.22.3/blob-csi-driver-v1.22.3.tgz
    version: v1.22.3
  - apiVersion: v1
    appVersion: v1.22.2
    created: "2025-01-20T08:06:19.032334755Z"
    description: Azure Blob Storage CSI driver
    digest: 259e66dc12db7310fe1c51e49c964398e0a6b7d511133916dd7d25f748f0b791
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.22.2/blob-csi-driver-v1.22.2.tgz
    version: v1.22.2
  - apiVersion: v1
    appVersion: v1.22.1
    created: "2025-01-20T08:06:19.031258148Z"
    description: Azure Blob Storage CSI driver
    digest: 8329d477d55c82f97bb09fb172c5f39a1677bedc13c7410bd93b306194516438
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.22.1/blob-csi-driver-v1.22.1.tgz
    version: v1.22.1
  - apiVersion: v1
    appVersion: v1.21.7
    created: "2025-01-20T08:06:19.03029075Z"
    description: Azure Blob Storage CSI driver
    digest: 1095721182d611e2556c611dd330758d8130fe66493db4f9189586a9219896d3
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.21.7/blob-csi-driver-v1.21.7.tgz
    version: v1.21.7
  - apiVersion: v1
    appVersion: v1.21.6
    created: "2025-01-20T08:06:19.02965159Z"
    description: Azure Blob Storage CSI driver
    digest: d5ba1f92795ec45970eb6e5fc54aa13a5684f9936216c064f8a3843bf722bf54
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.21.6/blob-csi-driver-v1.21.6.tgz
    version: v1.21.6
  - apiVersion: v1
    appVersion: v1.21.5
    created: "2025-01-20T08:06:19.029027916Z"
    description: Azure Blob Storage CSI driver
    digest: b403e9d49abfe076ecd83d6dd50166347ee4305f33dc840019474b2876723b9b
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.21.5/blob-csi-driver-v1.21.5.tgz
    version: v1.21.5
  - apiVersion: v1
    appVersion: v1.21.4
    created: "2025-01-20T08:06:19.0283896Z"
    description: Azure Blob Storage CSI driver
    digest: e4fa13670caf6b0d3e9fefa55d100daa439cd7187dabd45318ab03c7d4b17710
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.21.4/blob-csi-driver-v1.21.4.tgz
    version: v1.21.4
  - apiVersion: v1
    appVersion: v1.20.3
    created: "2025-01-20T08:06:19.027606202Z"
    description: Azure Blob Storage CSI driver
    digest: 8c2c20547b2e0e1b39d2f2efd04c1bd778f14af5feae2bda86d722dac3c02643
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.20.3/blob-csi-driver-v1.20.3.tgz
    version: v1.20.3
  - apiVersion: v1
    appVersion: v1.19.6
    created: "2025-01-20T08:06:19.026241311Z"
    description: Azure Blob Storage CSI driver
    digest: 0007ef225b5658d3989aa6fdc3a91a4b33696a438eee46ad9a675af615cbdf21
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.19.6/blob-csi-driver-v1.19.6.tgz
    version: v1.19.6
  - apiVersion: v1
    appVersion: v1.19.5
    created: "2025-01-20T08:06:19.025612312Z"
    description: Azure Blob Storage CSI driver
    digest: 183c3e5cd84b709f1455cc7c84ed5bd573e8a24149fd6442d38999835b0a1711
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.19.5/blob-csi-driver-v1.19.5.tgz
    version: v1.19.5
  - apiVersion: v1
    appVersion: v1.18.0
    created: "2025-01-20T08:06:19.024592586Z"
    description: Azure Blob Storage CSI driver
    digest: 3eac15488da5be7d1e78431929f7cda35bceb1af3fe107ffbd84606e047c9204
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.18.0/blob-csi-driver-v1.18.0.tgz
    version: v1.18.0
  - apiVersion: v1
    appVersion: v1.17.0
    created: "2025-01-20T08:06:19.022452013Z"
    description: Azure Blob Storage CSI driver
    digest: 22cfa17fc5e8d771ff8edd26729266a9a8ee55c0e150df85ef15698f7fe985e9
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.17.0/blob-csi-driver-v1.17.0.tgz
    version: v1.17.0
  - apiVersion: v1
    appVersion: v1.16.0
    created: "2025-01-20T08:06:19.021463935Z"
    description: Azure Blob Storage CSI driver
    digest: bf6249c0e3e3d3d009d4c79ceb7fda9a56c0565b969de753628792ea3ea5ece8
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.16.0/blob-csi-driver-v1.16.0.tgz
    version: v1.16.0
  - apiVersion: v1
    appVersion: v1.15.0
    created: "2025-01-20T08:06:19.020072362Z"
    description: Azure Blob Storage CSI driver
    digest: 8daa35cd4957695cb64b45da05a15b4020df5545a8ac44c4668dad4bba82c8a9
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.15.0/blob-csi-driver-v1.15.0.tgz
    version: v1.15.0
  - apiVersion: v1
    appVersion: v1.14.0
    created: "2025-01-20T08:06:19.019066372Z"
    description: Azure Blob Storage CSI driver
    digest: 442bc579b231aab626b9e474e2c0ed3f101d47d61c99aa9a7f863af7ce268d9d
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.14.0/blob-csi-driver-v1.14.0.tgz
    version: v1.14.0
  - apiVersion: v1
    appVersion: v1.13.0
    created: "2025-01-20T08:06:19.018128573Z"
    description: Azure Blob Storage CSI driver
    digest: b577b0b771138109aa90eb09d56fc07273ca0b584a263ee8f789e35796279f31
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.13.0/blob-csi-driver-v1.13.0.tgz
    version: v1.13.0
  - apiVersion: v1
    appVersion: v1.12.0
    created: "2025-01-20T08:06:19.017089216Z"
    description: Azure Blob Storage CSI driver
    digest: 124e87af2581b374b89a39940698620c23d3eae6dcee518d302461ffea93e9a8
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.12.0/blob-csi-driver-v1.12.0.tgz
    version: v1.12.0
  - apiVersion: v1
    appVersion: v1.11.0
    created: "2025-01-20T08:06:19.016156086Z"
    description: Azure Blob Storage CSI driver
    digest: 07c4d76017491b3d0bdd70de90e814096938bf7916da0c149c3805294bd57560
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.11.0/blob-csi-driver-v1.11.0.tgz
    version: v1.11.0
  - apiVersion: v1
    appVersion: v1.10.0
    created: "2025-01-20T08:06:19.015108844Z"
    description: Azure Blob Storage CSI driver
    digest: 79716efa958385adf57eb3570843e1b4512d8c801e8e070625e94264f3e917a9
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.10.0/blob-csi-driver-v1.10.0.tgz
    version: v1.10.0
  - apiVersion: v1
    appVersion: latest
    created: "2025-01-20T08:06:19.013837633Z"
    description: Azure Blob Storage CSI driver
    digest: 0b2261428f278495fb5d6103f77f95fb83078551e2b123215b8eddcd0bbcc143
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/latest/blob-csi-driver-v0.0.0.tgz
    version: v0.0.0
generated: "2025-01-20T08:06:19.012855567Z"
